#!/bin/sh
set -eu

if [ "${AGENTPORT_G1_CLEAN_ENV-}" != "1" ] ||
  [ "${NODE_OPTIONS+x}" = x ] ||
  [ "${ANTHROPIC_API_KEY+x}" = x ] ||
  [ "${CLAUDE_CODE_OAUTH_TOKEN+x}" = x ]; then
  printf 'G1_CLAUDE_HARNESS_FAILED\n' >&2
  exit 1
fi

run_clean() {
  /usr/bin/env -i \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    AGENTPORT_G1_CANDIDATE_REVISION="${AGENTPORT_G1_CANDIDATE_REVISION-}" \
    AGENTPORT_G1_CLAUDE="${AGENTPORT_G1_CLAUDE-}" \
    AGENTPORT_G1_CLAUDE_EXECUTABLE="${AGENTPORT_G1_CLAUDE_EXECUTABLE-}" \
    AGENTPORT_G1_CLAUDE_WORKSPACE="${AGENTPORT_G1_CLAUDE_WORKSPACE-}" \
    AGENTPORT_G1_CORE_DATA_PATH="${AGENTPORT_G1_CORE_DATA_PATH-}" \
    AGENTPORT_G1_G4_FIXTURE_ROOT="${AGENTPORT_G1_G4_FIXTURE_ROOT-}" \
    AGENTPORT_G1_DAEMON_USER="${AGENTPORT_G1_DAEMON_USER-}" \
    AGENTPORT_G1_INGRESS_GID="${AGENTPORT_G1_INGRESS_GID-}" \
    AGENTPORT_G1_LAUNCHER_CONFIG="${AGENTPORT_G1_LAUNCHER_CONFIG-}" \
    AGENTPORT_G1_LAUNCHER_SERVICE="${AGENTPORT_G1_LAUNCHER_SERVICE-}" \
    AGENTPORT_G1_LAUNCHER_SOCKET="${AGENTPORT_G1_LAUNCHER_SOCKET-}" \
    AGENTPORT_G1_LEDGER_DIRECTORY="${AGENTPORT_G1_LEDGER_DIRECTORY-}" \
    AGENTPORT_G1_LINUX="${AGENTPORT_G1_LINUX-}" \
    AGENTPORT_G1_RUNTIME_GID="${AGENTPORT_G1_RUNTIME_GID-}" \
    AGENTPORT_G1_RUNTIME_HOME="${AGENTPORT_G1_RUNTIME_HOME-}" \
    AGENTPORT_G1_RUNTIME_UID="${AGENTPORT_G1_RUNTIME_UID-}" \
    AGENTPORT_G1_RUNTIME_USER="${AGENTPORT_G1_RUNTIME_USER-}" \
    AGENTPORT_G1_WORKSPACE_IDENTITY="${AGENTPORT_G1_WORKSPACE_IDENTITY-}" \
    AGENTPORT_G1_WORKSPACE_PATH="${AGENTPORT_G1_WORKSPACE_PATH-}" \
    "$@"
}

run_clean /usr/local/bin/pnpm run build
run_clean /usr/local/bin/pnpm run build:fixtures
run_clean /usr/local/bin/node scripts/run-g1-claude.mjs
